### ISSUE TITLE
Realizar configuracion inicial del proyecto

### ISSUE THREAD

**Issue by NicolasFall** [LJVazquez/scrumbled#1]
- [x] ESlint configurado para ambos subproyectos
- [x] Rama master creada
- [x] Rama dev creada
- [x] Jest configurado para ambos subproyectos
- [x] Subproyecto para backend
- [x] Subproyecto para frontend

**Comment by LJVazquez** [comment]
Se completan todos los requerimientos con los siguientes PR:
https://github.com/LJVazquez/scrumbled/pull/4
https://github.com/LJVazquez/scrumbled/pull/5
